NUM_GPUS: 1
DATALOADER:
  NUM_WORKERS: 4
DATASET: "imagenet"
TRAIN:
  PATH: "/data/kai422/imagenet/train"
VAL:
  PATH: "/data/kai422/imagenet/val"
MODEL:
  ARCH: "resnet18"
  NUM_CLASSES: 1000
  DROPIT: True
DROPIT:
  STRATEGY: "fastmink"
  GAMMA: 0.8
  D: 16384
SOLVER:
  LR: 0.1
  BATCH_SIZE: 256
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1
  MAX_EPOCHS: 90
  MILESTONES: [30, 60]
CHECK_VAL_EVERY_N_EPOCH: 10