TRAIN:
  DATASET: "imagenet"
  PATH: "/disk4/imagenet-data/train"
VAL:
  DATASET: "imagenet"
  PATH: "/disk4/imagenet-data/train"
MODEL:
  ARCH: "vit_base_patch16_224"
  NUM_CLASSES: 1000
  DROPIT: True
DROPIT:
  STRATEGY: "fastmink"
  GAMMA: 0.9
  D: 16384
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  BATCH_SIZE: 64
  LR: 0.01
  MAX_EPOCHS: 8
  WARMUP_EPOCHS: 1
NUM_GPUS: 2
CHECK_VAL_EVERY_N_EPOCH: 1
