TRAIN:
  DATASET: "imagenet"
  PATH: "/data/kai422/imagenet/train"
VAL:
  DATASET: "imagenet"
  PATH: "/data/kai422/imagenet/val"
MODEL:
  ARCH: "vit_base_patch16_224"
  NUM_CLASSES: 1000
  DROPIN: True
DROPIN:
  STRATEGY: "fastmink"
  GAMMA: 0.9
  D: 16384
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  BATCH_SIZE: 512
  LR: 0.01
  MAX_EPOCHS: 8
  WARMUP_EPOCHS: 1
NUM_GPUS: 2
CHECK_VAL_EVERY_N_EPOCH: 1