DATASET: 'cifar100'
MODEL:
  ARCH: "resnet18"
  NUM_CLASSES: 100
  DROPIT: True
DROPIT:
  STRATEGY: "fastmink"
  GAMMA: 0.8
  D: 16384
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  BATCH_SIZE: 128
  LR: 0.1
  WEIGHT_DECAY: 0.0005
  GAMMA: 0.2
  MAX_EPOCHS: 200
  MILESTONES: [60, 120, 160]
NUM_GPUS: 1
CHECK_VAL_EVERY_N_EPOCH: 1
# CKPT: "outputs/cifar100/resnet18_fastminkx0.8/lightning_logs/version_1/checkpoints/epoch=199-step=77999.ckpt"