DATASET: 'cifar100'
MODEL:
  ARCH: "vit_base_patch16_224"
  NUM_CLASSES: 100
  DROPIN: True
DROPIT:
  STRATEGY: "fastmink"
  GAMMA: 0.9
  D: 16384
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  LR: 0.03
  BATCH_SIZE: 512
  MAX_EPOCHS: 100
  WARMUP_EPOCHS: 10
NUM_GPUS: 2
CHECK_VAL_EVERY_N_EPOCH: 1
